//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLU.Blog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public int AccountID { get; set; }
        public int PostID { get; set; }
        public Nullable<int> CommentLike { get; set; }
        public Nullable<int> CommentDislike { get; set; }
        public string CommentContent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> LangId { get; set; }
        public Nullable<int> Permission { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Post Post { get; set; }
    }
}
