//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLU.Blog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<bool> Like { get; set; }
        public Nullable<bool> DiskLike { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
